tag_generator:
  enable_index_page: false

math:
# Default (false) will load mathjax / katex script on demand.
# That is it only render those page which has `mathjax: true` in front-matter.
# If you set it to true, it will load mathjax / katex script EVERY PAGE.
  every_page: false

  mathjax:
    enable: false
    # Available values: none | ams | all
    tags: none
      
  katex:
    enable: true
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: true

giscus:
  enable: true
  repo: trailblazer-forward/trailblazer-forward.github.io
  repo_id: R_kgDOML7FQA
  category: Announcements
  category_id: DIC_kwDOML7FQM4C371L
  mapping: title
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  lang: zh-CN
  loading: lazy
  crossorigin: anonymous

avatar:
  url: https://avatars.githubusercontent.com/u/170234274?v=4
  rounded: false
  rotated: true

social:
  Github: https://github.com/trailblazer-forward || fab fa-github
  E-Mail: mailto:trailblazer.forward@outlook.com || fa fa-envelope

social_icons:
  enable: true
  icons_only: false
  transition: true

follow_me:
  RSS: /atom.xml || fa fa-rss

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
